### ISSUE TITLE
[BUG] 'connect' event does not fire; library does not load as a CommonJS module

### ISSUE THREAD

**Issue by ytcalifax** [qxb3/omegle.js#1]
I tried to use the example code to test stuff out and even that does not seem to work at all. Enabling debug mode just returns 'null' over and over again.

**Comment by qxb3** [comment]
Sorry for the inconvenience :(

Luckily i manage to fix it you can try it now by upgrading the package :)

**Comment by ytcalifax** [comment]
Hi and thanks for the quick fix! However, now when used, the library is still somewhat broken - it **refuses to load** when as a CommonJS module; even when loaded as a module, the **connected event did not fire** for me at all with the following code:
```js
import OmegleClient from 'omegle.js'

const client = new OmegleClient()

client.on('connected', () => {
  console.log('Connected')
})

client.on('message', (message) => {
  console.log(message)
})

client.connect({})
```

**Comment by ytcalifax** [comment]
**P.S.:** Also, making the server you connect to not always the same one is a good idea, as from what I notice you had to change it manually.

**Comment by qxb3** [comment]
Yeah sorry i'm still working on the commonjs support. For now add `"type": "module"` on the package.json

**Comment by ytcalifax** [comment]
What about the 'connect' event not firing and the static server domain? Even as a module they do not fire.

**Comment by qxb3** [comment]
For the the static server and the connect not firing I'll look and work it on later, I'm still in school rn 😅

**Comment by ytcalifax** [comment]
Alright, thanks a lot!

**Comment by qxb3** [comment]
Hihi! Looks like i have a freetime in here in school.

Can you try updating the package now and see if it works?

Oh and i added a new option in the OmegeClient constructor so that you can update the server. I will update the docs later

**Comment by ytcalifax** [comment]
Currently at university, I'll try it when I come back.

**Comment by ytcalifax** [comment]
The event seems to fire now, will report if anything else breaks.

**Comment by qxb3** [comment]
sure!
