### ISSUE TITLE
[BUG] Connection Without Mutual Topics

### ISSUE THREAD

**Issue by ytcalifax** [qxb3/omegle.js#3]
Hello again, @qxb3!

I have noticed a new issue with the current version of the package - it seems to be impossible to connect to Omegle.COM using the client **without** any mutual **topics** (or the new way of use has not been added to docs). The [change](https://github.com/qxb3/omegle.js/commit/5326e761b3f074a90b1998d6e46e7fa5fabd043e#diff-f8c69916507d5417972098e13b51c99c5668c34300ff4d785190d3cb3efe7828R32) you implemented with  commit ``5326e761b3f074a90b1998d6e46e7fa5fabd043e`` made it so whenever I do want to use the library without any topics I just get an error.

**P.S.:** axios has pushed a [broken release](https://github.com/axios/axios/issues/5298) that breaks GZIP handling, in turn messing up your library completely - I suggest limiting the library to v1.1.2 till they fix it, as this is the latest version that still seems to work.

**Comment by qxb3** [comment]
I'm pretty sure you can

```js
client.connect({
  topics: ['gaming']
)}
```

And if you want to get the mutual topics that you and the stranger matched you can get in on the `connected` event

```js
client.on('connected', (mutualTopics) => {
  console.log(mutualTopics) // ['gaming']
})
```

the mutualTopics will be undefined or an empty array i think, if you didn't pass any `topics` options in the connect method

**Comment by ytcalifax** [comment]
Ah, I see, before I just passed an empty list as the options and it worked... I guess I'll need to change it to the new way, so it works. Thanks anyways!

**Comment by qxb3** [comment]
Yeah... my bad xd im just coding without really thinking about consequences

**Comment by ytcalifax** [comment]
Nah, the issue in this case is that I failed to check that there is a new way to connect when the package broke for me due to it updating.
