### ISSUE TITLE
TypeError: message.sendMessage is not a function

### ISSUE THREAD

**Issue by atulbhatt-system32** [qxb3/omegle.js#4]
Message is a string yet how it can call a function to send Message?

```
client.on('message', (message) => {
  message.sendMessage(`[BOT] ${message}`)
})
```

**Comment by qxb3** [comment]
The correct way of sending message is by calling the `sendMessage()` function in the client

```js
const client = new Client()

client.on('message', (message) => {
  client.sendMessage(`[BOT] ${message}`)
})
```

**Comment by atulbhatt-system32** [comment]
Can you please fix this in the Readme and I suspect npm is also connect to this.

**Comment by qxb3** [comment]
The docs in the readme is updated and correct, there is no problem there

**Comment by qxb3** [comment]
Oh i see the problem now. I am looking at the docs and not the example, Thank u for pointing it out! :)

**Comment by qxb3** [comment]
Fixed :)

**Comment by atulbhatt-system32** [comment]
Welcome.

And thanks for this work.

Also, can you please add node version requirement as I was using older one and seems like you are using features like coalescing which are there in version later than 15 I suppose

**Comment by qxb3** [comment]
Just checked the docs and only node v14.0.0 up supports it. I will update the readme. Thank u!
